In [ ]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

In [ ]:
import pandas as pd
import numpy as np
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James'],
        'score': [12.5, 9, 16.5, np.nan],
        'attempts': [1, 3, 2, 3],
        'qualify': ['yes', 'no', 'yes', 'no']}
labels = ['a', 'b', 'c', 'd']
df = pd.DataFrame(exam_data , index=labels)
print("Orginal rows:")
print(df)
df = df.sort_values(by=['name', 'score'], ascending=[True,False])
print("Sorted data frame :")
print(df)

In [ ]:
import pandas as pd

data = {
    'A': ['A1', 'A2', 'A3', 'A4', 'A5'],
    'B': ['B1', 'B2', 'B3', 'B4', 'B5'],
    'C': ['C1', 'C2', 'C3', 'C4', 'C5'],
    'D': ['D1', 'D2', 'D3', 'D4', 'D5'],
    'E': ['E1', 'E2', 'E3', 'E4', 'E5']}

df = pd.DataFrame(data)
df.drop(['A'], axis=1)

In [ ]:
# importing the modules
import pandas as pd
import numpy as np

students = {'Student': ['Amit', 'Cody','Darren', 'Drew'],
            'RollNumber': [1, 5, 10, 15],
            'Grade': ['A', 'C', 'F', 'B']}
df = pd.DataFrame(students, columns =['Student', 'RollNumber','Grade'])
print("Original DataFrame")
print(df)
df.to_csv('Students.csv', sep ='\t')
new_df = pd.read_csv('Students.csv')
print('Data from Students.csv:')
print(new_df)